source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

project 'Plime.xcodeproj'
inhibit_all_warnings!

use_frameworks!

target :Plime do

pod 'AFNetworking'
pod 'Masonry'
pod 'MJRefresh'
pod 'MJExtension'
pod 'MBProgressHUD'
pod 'SDWebImage'

end
